
name: testing
on:
  push: 
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: dotnet 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: nuget
        run: |
          # Download the latest stable `nuget.exe` to `/usr/local/bin`
          curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          # Create as alias for nuget
          alias nuget="mono /usr/local/bin/nuget.exe"
      - name: restore
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/mynameischandra/index.json" \
          --name "GitHubPackages" \
          --username "chandrasekhar7" \
          --password "${{ secrets.NUGET_AUTH_TOKEN }}" \
          --store-password-in-clear-text
          dotnet restore
